config/routes.rb
Rails.application.routes.draw do
    get '/movies' => 'movies#index'
get '/movies/:id' => 'movies#show', as: :movie
	get '/actors' => 'actors#index'
	get '/actors/:id' => 'actors#show', as: :actor

end

app/models/actor.rb
class Actor < ActiveRecord::Base

has_many :parts 
has_many :movies, through: :parts
    
# has_many :friends # Friend(actor_id, name)

# Has-many relationship without join model
# has_many :movies (and the inverse on Actor model)
# Create table called actor_movies (actor_id, movie_id)    
    
# Apple Orange => apple_oranges (apple_id, orange_id)
# Car Boat => boat_cars (car_id, boat_id)

end

app/models/movie.rb
class Movie < ActiveRecord::Base
    has_many :parts 
    has_many :actors, through: :parts
end

app/models/part.rb
class Part < ActiveRecord::Base
    belongs_to :movie 
    belongs_to :actor
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    
    
	def index
		@actors = Actor.all
	end
	
	def show
            @actor = Actor.find(params[:id])
            @movies = @actor.movies
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
    
 def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row">
					<% @actors.each do |actor| %>
          <div class="actor col-xs-2">
              
             <IMG SRC"<%=actor.image%>"/>
            <h3> <%=actor.first_name%> <%=actor.last_name%> </h3>
            <p> <%=actor.bio%> </p>
          <p>    <%= link_to "Learn more", actor_path(actor) %></p>
    </div>
          </div>
          <% end %>
          
      </div>
</div>

app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="actor">
      <IMG SRC="<%=@actor.image%>"/>
      <div class="info">
        <h3 class="actor-name"><%=@actor.first_name %><%=@actor.last_name%>  </h3>
        <p class="actor-bio"> <%=@actor.bio%> </p>
      </div>
    </div>

    <h2>Movies</h2>
    <% @movies.each do |m| %>
    <div class="movie">
      <IMG SRC="<%=m.image%>"/>
      <h3 class="movie-title"> <%=m.title%> </h3>
      <p class="movie-release-year"> <%=m.release_year%> </p>
      <p class="movie-plot"> <%=m.plot%> </p>
        <%= link_to "Learn more", movie_path(m) %>
    </div>
      <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<div class="hero">
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
  <h2>Popular Films</h2>
	<% @movies.each do |m| %>  
    <div class="movie">
     <IMG SRC="<%= m.image %>" />
      <h3> <%= m.title %>e </h3>
      <p>  <%= m.release_year %> </p>
        <%= link_to "Learn more", movie_path(m) %>
    </div>
    
      <% end %>
  </div>
</div>

app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">
      
      <!-- Display the movie's info here -->
      <div class="info">
          <IMG SRC="<%=@movie.image%>"/>
          <h3 class="movie-title"><%=@movie.title%>  </h3>
          <p class="movie-release-year"><%=@movie.release_year%>  </p>
        <p class="movie-plot">  <%=@movie.plot%></p>
      </div>
    </div>

    <h2>Cast</h2>
      
      <% @actors.each do |actor|  %>
    <div class="actor">
        <%= actor.image %>
        <h3 class="actor-name">  <%= actor.first_name %>  <%= actor.last_name %></h3>
      <p class="actor-bio">   <%= actor.bio %> </p>
         <%= link_to "Learn more", actor_path(actor) %>
    </div>
      <% end %>

  </div>
</div>